### ISSUE TITLE
O caminho do certificado não está sendo usado

### ISSUE THREAD

**Issue by vanderson139** [nezkal/Cielo#4]
Alterei a classe CieloService, na linha 259 e deu certo. Ficou assim:

        if (isset($options['loja']) && $options['loja'] instanceof Loja) {
            $this->loja = $options['loja'];
            $this->ssl = $options['loja']->getSslCertificado();
        }

**Comment by nezkal** [comment]
Ok, consegue mandar um pull request ?

**Comment by vanderson139** [comment]
ok, feito.
