### ISSUE TITLE
Call to a member function getName() on a non-object

### ISSUE THREAD

**Issue by jammersonf** [nezkal/Cielo#9]
Sempre que faço uma compra, ele me retorna esse erro na transação.
Sabe onde possa ser o problema?

![untitled](https://cloud.githubusercontent.com/assets/2231447/8436975/7ca9b474-1f32-11e5-92d8-9a3e8c6bd3a8.png)

**Comment by jarjar123** [comment]
Provavelmente a resposta da Cielo não é um XML válido.
Seria interessante se vc enviasse a mensagem de retorno da Cielo.

    Mage::log('Response: ' . $result);

**Comment by jammersonf** [comment]
Eu dei um var_dump($result), e está vindo vazio.

Fiz um debug no código, antes de `$requisicao = $this->enviaRequisicao($xml);` eu vi que o xml está indo normalmente. O problema está sendo no retorno dessa requisição.

![untitled](https://cloud.githubusercontent.com/assets/2231447/8441346/f9aa3384-1f4d-11e5-8f0b-371af08ee931.png)

**Comment by jarjar123** [comment]
Sua requisição parece certa.
Vc colocou o `var_dump($result);` logo após esse trecho?

        // Faz a requisição HTTP
        $result = utf8_encode(curl_exec($_curl));

**Comment by jammersonf** [comment]
Fiz sim, o retorno do $result é: `string '' (length=0)`

**Comment by jarjar123** [comment]
Então o problema é mais embaixo.
Se vc tiver certeza de que não fez nenhuma alteração nesta biblioteca, sugiro começar verificando se teu servidor está ok.
* Verificar se a biblioteca CURL está funcionando.
* Verificar se algum firewall está ativo, e atrapalhando teu trabalho.
* etc

**Comment by jammersonf** [comment]
Realmente eu joguei no serv de produção pra testar e foi normalmente, não sei ainda o que aconteceu com o local.

Agradeço a atenção!
